config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, only: [:index, :new, :create, :show]
  resources :friends, only: [:index, :new, :create]

  get 'welcome/index'
  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  post 'users/create', as: 'create_user'
  get 'sents/index'

  root 'welcome#index'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :from, class_name: 'User', :foreign_key => 'from_id'
  belongs_to :to, class_name: 'User', :foreign_key => 'to_id'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', :foreign_key => 'sender_id'
  belongs_to :recipient, class_name: 'User', :foreign_key => 'recipient_id'

  validates :body, presence: true, length: { minimum: 5 }

  def mark_read
    self.read = true
    self.read_at = DateTime.now
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id', dependent: :destroy
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'recipient_id'

  has_many :friends, foreign_key: 'from_id', dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }
  validates :password, presence: true, length: { minimum: 3 }, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :email, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in? # these methods can be used in views

  def sign_in(user)
    session[:user_id] = user.id
  end

  def logout(user)
    session[:user_id] = nil
    redirect_to root_path
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id]) # same as @current_user = @current_user || User.find(...)
  end

  def signed_in?
    current_user
  end

  def require_user
    redirect_to login_path, flash: {error: 'Please log in first'} unless signed_in?
  end

  def redirect_to_messages_if_signed_in
    redirect_to messages_path if signed_in?
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :require_user, only: [:create]

  def create
    user = User.find_by_id(params[:id])
    if !user
      redirect_to users_path, flash: {error: "User not found"}
    else
      friend = Friend.new

      friend.from_id = current_user.id
      friend.to_id = user.id
      if friend.save
        redirect_to users_path, flash: {success: 'Add friend successfully!'}
      else
        render friend.errors
        redirect_to users_path, flash: {error: 'Add friend failed!'}
      end
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user, only: [:index, :new, :create, :show]

  def index
    @messages = Message.where(recipient: current_user).order(created_at: :desc)
  end

  def show
    @message = Message.find_by_id(params[:id])
    if @message.nil?
      redirect_to messages_path, flash: {error: "Message not found"}
    elsif @message.recipient != current_user
      redirect_to messages_path, flash: {error: "You only can view your received messages"}
    elsif @message.read
      flash.now[:alert] = "The message was read"
    else
      @message.mark_read
    end
  end

  def new
    @message = Message.new
  end

  def create
    recipient = User.find_by(id: params[:message][:recipient])

    if !recipient
      flash.now.error = "Please choose a recipient"
    else
      Message.create(sender: current_user, recipient: recipient, body: params[:message][:body], attachment: params[:message][:attachment])
      redirect_to messages_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :recipient)
  end
end

app/controllers/sents_controller.rb
class SentsController < ApplicationController
  before_action :require_user, only: [:index]

  def index
    @messages = Message.where(sender: current_user).order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [:destroy]
  before_action :redirect_to_messages_if_signed_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to messages_path, flash: {success: "Welcome back <strong>#{current_user.name}</strong>!"}
    else
      redirect_to login_path, flash: {error: 'Email or password is incorrect'}
    end
  end

  def destroy
    logout(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:index]
  before_action :redirect_to_messages_if_signed_in, only: [:new, :create]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to messages_path, flash: {success: "Welcome <strong>#{current_user.name}</strong>!"}
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sents_helper.rb
module SentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<div class="portfolio-page container-fluid">

  <div class="row">

    <!--( a ) Portfolio Page Fixed Image Portion -->

    <div class="image-container col-md-3 col-sm-12">
      <div class="mask">
      </div>
      <div class="main-heading">
        <h1>Messages</h1>
      </div>
    </div>

    <!--( b ) Portfolio Page Content -->

    <div class="content-container col-md-9 col-sm-12">

      <%= render partial: "shared/flash", flash: flash %>

      <!--( A ) Portfolio -->

      <div class="portfolio clearfix full-height">
        <h2 class="small-heading">MY MESSAGES</h2>

        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                <div class="project-container">
                    <div class="row">
                        <div class="project-controls">
                          <ul class="messages-nav">
                            <li><a href="" class="active">Incoming messages</a></li>
                            <li><a href="">Sent messages</a></li>
                            <li><a href="">New message</a></li>
                            <li><a href="">Add friends</a></li>
                          </ul>
                        </div>

                        <!-- Portfolio Control Buttons [ END ] -->

                        <div id="projects" class="projet-items clearfix">
                          <% @messages.each do |message| %>
                          <div class="bd-callout <%= if message.read then 'bd-callout-info' else 'bd-callout-danger' end %>">
                            <h4><%= message.sender %></h4>
                            <p><%= message.body %></p>
                          </div>
                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

      </div>

      <!-- Footer -->

      <%= render partial: "shared/footer" %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#projects').mixItUp();
  });
</script>

app/views/messages/new.html.erb
<div class="portfolio-page container-fluid">
  <div class="row">
    <!--( a ) Contact Page Fixed Image Portion -->

    <div class="image-container col-md-3 col-sm-12">
      <div class="mask">
      </div>
      <div class="main-heading">
        <h1>messages</h1>
      </div>
    </div>

    <!--( b ) Contact Page Content -->

    <div class="content-container col-md-9 col-sm-12">

      <%= render partial: "shared/flash", flash: flash %>

      <div class="portfolio clearfix full-height">
        <h2 class="small-heading">CREATE NEW MESSAGE</h2>

        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                <div class="project-container">
                    <div class="row">
                        <div class="project-controls">
                          <ul class="messages-nav">
                            <li><%= link_to 'Incoming messages', messages_path %></li>
                            <li><%= link_to 'Sent messages', sents_index_path %></li>
                            <li><%= link_to 'New message', new_message_path, class: 'active' %></li>
                            <li><%= link_to 'Add friends', users_path %></li>
                          </ul>
                        </div>

                        <!-- Portfolio Control Buttons [ END ] -->

                        <div id="projects" class="projet-items clearfix">
                          <%= simple_form_for @message, html: {class: 'contact-form"'} do |f| %>

                            <div class="col-md-6 col-sm-6">
                              <div class="form-group">
                                <%= f.input :recipient, collection: current_user.friends, :label_method => :name, :value_method => :id, prompt: false, class: 'form-control' %>
                              </div>
                            </div>

                            <div class="col-md-12 col-sm-12">
                              <%= f.input :body, label: false, placeholder: 'Your message', class: 'form-control', required: 'required', as: :text %>
                            </div>

                            <div class="col-md-4 col-xs-12">
                              <%= f.submit 'Send', class: 'btn btn-send' %>
                            </div>

                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

      <!-- ( D ) Footer -->

      <%= render partial: "shared/footer" %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="portfolio-page container-fluid">

  <div class="row">

    <!--( a ) Portfolio Page Fixed Image Portion -->

    <div class="image-container col-md-3 col-sm-12">
      <div class="mask">
      </div>
      <div class="main-heading">
        <h1>Messages</h1>
      </div>
    </div>

    <!--( b ) Portfolio Page Content -->

    <div class="content-container col-md-9 col-sm-12">

      <%= render partial: "shared/flash", flash: flash %>

      <!--( A ) Portfolio -->

      <div class="portfolio clearfix full-height">
        <h2 class="small-heading">MY MESSAGES</h2>

        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                <div class="project-container">
                    <div class="row">
                        <div class="project-controls">
                          <ul class="messages-nav">
                            <li><%= link_to 'Incoming messages', messages_path, class: 'active' %></li>
                            <li><%= link_to 'Sent messages', sents_index_path %></li>
                            <li><%= link_to 'New message', new_message_path %></li>
                            <li><%= link_to 'Add friends', users_path %></li>
                          </ul>
                        </div>

                        <!-- Portfolio Control Buttons [ END ] -->

                        <div id="projects" class="projet-items clearfix">
                        <% if @message %>
                            <div class="col-md-6" style="text-align: left">
                              <h6>Sender: <b><%= @message.sender.name %></b></h6>
                              <h6>Sent at: <b><%= @message.created_at.strftime("%A, %B %d, %H:%M") %></b></h6>
                              <hr>
                              <p>
                                <%= @message.body %>
                              </p>
                            </div>
                        <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

      </div>

      <!-- Footer -->

      <%= render partial: "shared/footer" %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#projects').mixItUp();
  });
</script>

app/views/sents/index.html.erb
<div class="portfolio-page container-fluid">

  <div class="row">

    <!--( a ) Portfolio Page Fixed Image Portion -->

    <div class="image-container col-md-3 col-sm-12">
      <div class="mask">
      </div>
      <div class="main-heading">
        <h1>Messages</h1>
      </div>
    </div>

    <!--( b ) Portfolio Page Content -->

    <div class="content-container col-md-9 col-sm-12">

      <%= render partial: "shared/flash", flash: flash %>

      <!--( A ) Portfolio -->

      <div class="portfolio clearfix full-height">
        <h2 class="small-heading">MY MESSAGES</h2>

        <div class="row">
            <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
                <div class="project-container">
                    <div class="row">
                        <div class="project-controls">
                          <ul class="messages-nav">
                            <li><%= link_to 'Incoming messages', messages_path %></li>
                            <li><%= link_to 'Sent messages', sents_index_path, class: 'active' %></li>
                            <li><%= link_to 'New message', new_message_path %></li>
                            <li><%= link_to 'Add friends', users_path %></li>
                          </ul>
                        </div>

                        <!-- Portfolio Control Buttons [ END ] -->

                        <div id="projects" class="projet-items clearfix">
                        <% @messages.each do |message| %>
                          <% if message.read %>
                          <div class="bd-callout bd-callout-info">
                            <h4><%= message.sender.name %></h4>
                            <p>
                              <%= message.body %>
                              <br><small class="text-muted pull-right">Read at <em><%= message.read_at.strftime("%A, %B %d, %H:%M") %></em></small>
                            </p>
                          </div>
                          <% else %>
                          <div class="bd-callout bd-callout-danger">
                            <h4><%= message.sender.name %></h4>
                            <p>
                              <%= message.body %>
                              <br><small class="text-muted pull-right"><em>This message is not read</em></small>
                            </p>
                          </div>
                          <% end %>
                        <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

      </div>

      <!-- Footer -->

      <%= render partial: "shared/footer" %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#projects').mixItUp();
  });
</script>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message.html_safe %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer clearfix">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
      <div class="row">
        <div class="col-md-6 col-sm-12 col-xs-12">
          <p class="copyright">Copyright &copy; 2015
            <a href="#">CoderChat</a>
          </p>
        </div>

        <div class="col-md-6 col-sm-12 col-xs-12">
          <p class="author">
            Theme by <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="service-page container-fluid">
  <div class="row">
    <!--( a ) Portfolio Page Fixed Image Portion -->

    <div class="image-container col-md-3 col-sm-12">
      <div class="mask">
      </div>
      <div class="main-heading">
        <h1>People</h1>
      </div>
    </div>

    <!--( b ) Portfolio Page Content -->

    <div class="content-container col-md-9 col-sm-12">

      <%= render partial: "shared/flash", flash: flash %>

      <!--( A ) Portfolio -->

      <div class="clearfix full-height">
        <h2 class="small-heading">MAKE FRIENDS</h2>

        <div class="row">
          <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
            <div class="row">
              <div class="project-controls">
                <ul class="messages-nav">
                  <li><%= link_to 'Incoming messages', messages_path %></li>
                  <li><%= link_to 'Sent messages', sents_index_path %></li>
                  <li><%= link_to 'New message', new_message_path %></li>
                  <li><%= link_to 'Add friends', users_path, class: 'active' %></li>
                </ul>
              </div>

              <% User.all.each do |user| %>
                <% if !current_user.friends.include?(user) && current_user != user %>
                  <%= form_tag friends_path, method: "post", class: 'form-inline' do %>
                    <input type="hidden" name="id" value="<%= user.id %>">
                    <span><%= user.name.titleize %></span>
                    <button type="submit" class="btn btn-link"><%= "Add friend" %></button>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <!-- Footer -->

      <%= render partial: "shared/footer" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="contact-page container-fluid">
  <div class="row">
    <!--( a ) Contact Page Fixed Image Portion -->

    <div class="image-container col-md-3 col-sm-12">
      <div class="mask">
      </div>
      <div class="main-heading">
        <h1>sign up</h1>
      </div>
    </div>

    <!--( b ) Contact Page Content -->

    <div class="content-container col-md-9 col-sm-12">

      <%= render partial: "shared/flash", flash: flash %>

      <!--( A ) Contact Form -->

      <div class="clearfix full-height">
          <h2 class="small-heading">CREATE AN ACCOUNT</h2>
          <div class="row">
            <div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
              <div class="row">
                <%= simple_form_for @user, :url => create_user_path, html: {class: 'contact-form"'} do |f| %>

                  <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                      <%= f.input :name, placeholder: 'Name', class: 'form-control', required: 'required' %>
                    </div>
                  </div>

                  <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                      <%= f.input :email, placeholder: 'Email', class: 'form-control', required: 'required' %>
                    </div>
                  </div>

                  <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                      <%= f.input :password, placeholder: 'Password', class: 'form-control', required: 'required' %>
                    </div>
                  </div>

                  <div class="col-md-6 col-sm-6">
                    <div class="form-group">
                      <%= f.input :password_confirmation, placeholder: 'Password Confirmation', class: 'form-control', required: 'required' %>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <%= f.submit 'Register', class: 'btn btn-send' %>
                  </div>

                <% end %>
              </div>
            </div>
          </div>
      </div>

      <!-- ( D ) Footer -->

      <%= render partial: "shared/footer" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<!-- Preloader -->

<div id="preloader">
  <div class="loader">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>

<div class="home-page">

  <!-- Introduction -->

  <div class="introduction">
      <!-- <div class="mask">
      </div> -->
      <div class="intro-content">
          <!-- <h1>HELLO<br>
          I'M <span>JOHN</span> DOE</h1> -->
          <h1>
              Hi, We are
          </h1>
          <span>joyChat</span><span class="number">3</span>
          <p class="slogan-text text-capitalize">We bring JOY to Everyone</p>

          <!-- <div class="social-media hidden-xs">
              <a href="#" class="fa fa-facebook" data-toggle="tooltip" title="Facebook"></a>
              <a href="#" class="fa fa-twitter" data-toggle="tooltip" title="Twitter"></a>
              <a href="#" class="fa fa-plus" data-toggle="tooltip" title="Google+"></a>
              <a href="#" class="fa fa-linkedin" data-toggle="tooltip" title="Linkedin"></a>
              <a href="#" class="fa fa-behance" data-toggle="tooltip" title="Behance"></a>
              <a href="#" class="fa fa-flickr" data-toggle="tooltip" title="Flicker"></a>
              <a href="#" class="fa fa-instagram" data-toggle="tooltip" title="Instagram"></a>
          </div> -->
      </div>

      <!-- Social Media Icons [ END ] -->
  </div>

  <!-- Navigation Menu -->

  <div class="menu">
    <!-- Single Navigation Menu Button [ END ]  -->

    <div class="service-btn">
      <%= image_tag 'service.jpg' %>
      <div class="mask">
      </div>
      <div class="heading">
        <i class="ion-ios-people-outline hidden-xs"></i>
        <h2><%= link_to 'People', users_path %></h2>
      </div>
    </div>

    <!-- Single Navigation Menu Button [ END ]  -->

    <div class="contact-btn">
      <%= image_tag 'contact.jpg' %>
      <div class="mask">
      </div>
      <div class="heading">
        <i class="ion-email hidden-xs"></i>
        <h2><%= link_to 'Messages', messages_path %></h2>
      </div>
    </div>

    <!-- Single Navigation Menu Button -->

    <div class="portfolio-btn">
      <%= image_tag 'portfolio.jpg' %>
      <div class="mask">
      </div>
      <div class="heading">
        <% unless signed_in? %>
        <i class="ion-log-in hidden-xs"></i>
        <h2><%= link_to 'Sign In', login_path %></h2>
        <% else %>
        <i class="ion-person-add hidden-xs"></i>
        <h2><%= link_to 'Friends', root_path %></h2>
        <% end %>
      </div>
    </div>

    <!-- Single Navigation Menu Button [ END ]  -->

    <div class="profile-btn">
      <%= image_tag 'about.jpg', style: 'width:100%; height:100%;' %>
      <div class="mask">
      </div>
      <div class="heading">
        <% unless signed_in? %>
        <i class="ion-beer hidden-xs"></i>
        <h2><%= link_to 'Sign Up', register_path %></h2>
        <% else %>
        <i class="ion-log-out hidden-xs"></i>
        <h2><%= link_to 'Sign Out', logout_path %></h2>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
/*  ------------------
Remove Preloader
------------------  */

$(window).load(function () {
    $('#preloader').delay(350).fadeOut('slow', function () {
        // $('.profile-page, .portfolio-page, .service-page, .contact-page').hide();
    });
});
</script>